#!/bin/bash
export HOME=/massbit/massbitroute/app/src/tmp
ASDF=/massbit/massbitroute/app/gbc/bin/.asdf
GRAFANA_VERSION=v8.2.1
GRAFANA_DIR=$ASDF/installs/grafana/$GRAFANA_VERSION
PROMETHEUS_VERSION=v2.30.3
PROMETHEUS_DIR=$ASDF/installs/prometheus/$PROMETHEUS_VERSION
_clean_vts() {
	h=$1
	curl http://${h}'/__internal_status_vhost/control?cmd=delete&group=filter&zone=*'
}
_clean_prom() {
	h=$1
	if [ -z "$h" ]; then h="127.0.0.1:9090"; fi
	curl -X POST -g http://${h}'/__internal_prometheus/api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"}'
	curl -X POST -g http://${h}'/__internal_prometheus/api/v1/admin/tsdb/clean_tombstones'
}

_git_config() {
	git config --global user.name "Vu Tran"
	git config --global user.email "baysao@gmail.com"

	# 	cat >$HOME/.gitconfig <<EOF
	# [user]
	# 	email = baysao@gmail.com
	# 	name = Vu Tran
	# EOF
}
_reload() {
	SITE_ROOT=$1
	if [ -z "$SITE_ROOT" ]; then
		SITE_ROOT=$(dirname $(realpath $0))
		SITE_ROOT=$SITE_ROOT/../
	fi
	if [ ! -f "$SITE_ROOT/tmp/nginx.pid" ]; then
		echo $(pgrep nginx | head -1) >$SITE_ROOT/tmp/nginx.pid
	fi
	$SITE_ROOT/bin/openresty/nginx/sbin/nginx -p $SITE_ROOT -c nginx.conf -s reload
	#	/massbit/massbitroute/app/src/cmd_server nginx -s reload
	#	/massbit/massbitroute/app/src/cmd_server update
}
_remove() {
	conf=$1
	if [ ! -f "$conf "]; then exit 1; fi
	cd $(dirname $(realpath $0))
	_git_config
	git rm -f "$conf"
	git commit -m "$conf"
	git push
	_reload
}
_commit() {
	conf=$1
	if [ ! -f "$conf "]; then exit 1; fi
	cd $(dirname $(realpath $0))
	_git_config
	git add -f "$conf"
	git commit -m "$conf"
	git push
	_reload
}
_pull() {
	dir=$1
	cd $dir
	#tmp=$(mktemp)
	git pull | grep "updating"
	#>$tmp
	#grep -i "updating" $tmp
	if [ $? -eq 0 ]; then
		#		grep -i "conf.d" $tmp
		_reload
		# if [ $? -ne 0 ]; then
		# 	/massbit/massbitroute/app/src/cmd_server update
		# fi
		#		/massbit/massbitroute/app/src/cmd_server nginx -s reload
	fi
	#rm $tmp
}
_service_grafana() {
	SITE_ROOT=$1
	mkdir -p _SITE_ROOT_/data/grafana
	GRAFANA_DIR=$SITE_ROOT/bin/grafana/$GRAFANA_VERSION
	exec $GRAFANA_DIR/bin/grafana-server -config $SITE_ROOT/etc/grafana/stat.ini -homepath $GRAFANA_DIR
}
_service_prometheus() {
	SITE_ROOT=$1
	mkdir -p _SITE_ROOT_/data/prometheus
	PROMETHEUS_DIR=$SITE_ROOT/bin/prometheus/$PROMETHEUS_VERSION
	exec $PROMETHEUS_DIR/bin/prometheus --web.enable-admin-api --config.file=$SITE_ROOT/etc/prometheus/stat.yml --web.listen-address="127.0.0.1:33339" --web.external-url http://127.0.0.1:33339/__internal_prometheus --web.enable-lifecycle --storage.tsdb.path $SITE_ROOT/data/prometheus
}
loop() {
	while true; do
		$@
		sleep 1
	done

}
_run() {
	SITE_ROOT=$1
	if [ -z "$SITE_ROOT" ]; then
		SITE_ROOT=$(dirname $(realpath $0))
		SITE_ROOT=$SITE_ROOT/../
	fi

	$SITE_ROOT/bin/openresty/nginx/sbin/nginx -p $SITE_ROOT -c nginx.conf
}

$@
