#!/bin/bash
TYPE="node"
SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
export DEBIAN_FRONTEND=noninteractive

export HOME=$SITE_ROOT

if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw >/dev/null; fi

source $SITE_ROOT/scripts/base.sh >/dev/null
# _load_env $SITE_ROOT
cd $SITE_ROOT

mbr_root=/massbit/massbitroute/app
service_dir=$mbr_root/src/sites/services

log_install=$SITE_ROOT/logs/install.log
GIT_PUBLIC_URL="https://github.com"
export MBR_ENV=${MBR_ENV:-dev}
_repo() {
	REPOS="$mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git|$MBR_ENV \
$SITE_ROOT|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_${TYPE}.git|$MBR_ENV \
$service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MBR_ENV"

}
_repo

_debug() {
	timeout 30 $SITE_ROOT/scripts/debug.sh
}

_tune() {
	echo 2000000 >/proc/sys/fs/nr_open
	echo 2000000 >/proc/sys/fs/file-max
	ulimit -n 2000000
	cp /massbit/massbitroute/app/gbc/conf/limits.conf /etc/security/limits.d/mbr.conf
	cp /massbit/massbitroute/app/gbc/conf/sysctl.conf /etc/sysctl.d/99-mbr.conf
	sysctl -p
	cat >/etc/logrotate.d/massbit <<EOF
$SITE_ROOT/logs/access/*.log
$SITE_ROOT/logs/nginx/*.log
$SITE_ROOT/logs/*.log {
       daily
       rotate 1
       delaycompress
       compress
       notifempty
       missingok
       sharedscripts
        postrotate
                [ -f $SITE_ROOT/tmp/nginx.pid ] && kill -USR1 \$(cat $SITE_ROOT/tmp/nginx.pid)
        endscript
}
EOF
}

_init() {
	if [ ! -f "$SITE_ROOT/.env" ]; then
		echo "$MBR_ENV" >$SITE_ROOT/.env
	fi
	source $SITE_ROOT/.env >/dev/null
	_git_clone $GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git /massbit/massbitroute/app/gbc
	bash $SITE_ROOT/cmd_server _env
	source $SITE_ROOT/.env_raw >/dev/null
	_repo
}
_prepare() {
	echo "Prepare"
	mkdir -p $SITE_ROOT/etc $SITE_ROOT/logs/error $SITE_ROOT/logs/access $SITE_ROOT/logs/nginx $SITE_ROOT/db $SITE_ROOT/tmp $SITE_ROOT/http.d
	# rm -rf $SITE_ROOT/tmp/*

}

_install_repos() {
	_git_config
	_repo
	for _pathgit in $REPOS; do
		_path=$(echo $_pathgit | cut -d'|' -f1)
		_url=$(echo $_pathgit | cut -d'|' -f2)
		_branch=$(echo $_pathgit | cut -d'|' -f3)
		_git_clone $_url $_path $_branch
	done
}
_maintain() {
	rm $SITE_ROOT/logs/*M
	truncate -s 0 $SITE_ROOT/logs/*
	truncate -s 0 $SITE_ROOT/logs/access/*
	truncate -s 0 $SITE_ROOT/logs/nginx/*
	truncate -s 0 /var/log/atop/*
	bash $SITE_ROOT/mbr node nodeinfo
	rm /tmp/test_speed_* /tmp/check_speed
	_debug
}
_supervisor() {
	ln -sf /massbit/massbitroute/app/gbc /massbit/massbitroute/app/src/gbc
	ln -sf /massbit/massbitroute/app/gbc/bin/openresty /usr/local/openresty
	apt-get update
	apt-get install -y ca-certificates curl git apache2-utils supervisor jq python-is-python2 libssl-dev libmaxminddb-dev
	systemctl enable supervisor
	systemctl start supervisor
	mkdir -p /etc/supervisor/conf.d
	cp supervisor.conf /etc/supervisor/conf.d/${TYPE}.conf
	supervisorctl update
}
_install() {
	_init >>$log_install
	_prepare >>$log_install
	_install_repos >>$log_install
	_supervisor >>$log_install
}

_load_config() {
	PORTAL_URL=$(cat $SITE_ROOT/vars/PORTAL_URL)
	DATA_URI=$(cat $SITE_ROOT/vars/DATA_URI)
	mkdir -p $SITE_ROOT/http.d
	# $SITE_ROOT/mbr node nodeinfo
	is_reloading=0
	id=$(cat $SITE_ROOT/vars/ID)
	if [ -z "$id" ]; then return $is_reloading; fi

	curl -skSfL $PORTAL_URL/deploy/${TYPE}conf/${id}.conf -o http.d/${id}.conf.new >/dev/null
	if [ ! -f "http.d/${id}.conf" ]; then
		touch http.d/${id}.conf
	fi

	diff -s http.d/${id}.conf http.d/${id}.conf.new
	if [ $? -ne 0 ]; then
		mv http.d/${id}.conf.new http.d/${id}.conf
		is_reloading=1
	fi

	if [ -n "$DATA_URI" ]; then
		sed -i "s/proxy_pass ;/proxy_pass $DATA_URI;/g" http.d/${id}.conf
		sed -i "s/proxy_pass ;/proxy_pass $DATA_URI;/g" http.d/node.conf0
	fi
	if [ -n "$id" ]; then
		sed "s/__NODE_ID__/$id/g" etc/node.conf >http.d/node.conf0
	fi

	if [ -n "$DOMAIN" ]; then
		sed -i "s/__DOMAIN__/$DOMAIN/g" http.d/node.conf0
	fi

	$SITE_ROOT/cmd_server start all
	return $is_reloading
}
_add_host_file() {
	PORTAL_URL=$(cat $SITE_ROOT/vars/PORTAL_URL)
	if [ ! -f "/etc/hosts.bk" ]; then
		sed '/.mbr/d' /etc/hosts >/etc/hosts.bk
	fi
	sed '/</d' /etc/hosts -i /etc/hosts.bk
	cat /etc/hosts.bk >/tmp/hosts
	curl -s $PORTAL_URL/deploy/info/hosts -o /tmp/hosts.1
	if [ -f "/tmp/hosts.1" ]; then
		cat /tmp/hosts.1 >>/tmp/hosts
		cat /tmp/hosts >/etc/hosts
		rm /tmp/hosts.1
	fi
}

_reload() {

	_maintain

	id=$(cat $SITE_ROOT/vars/ID)
	# _sc=$SITE_ROOT/${TYPE}deploy/debug/${id}.sh
	# echo "Script path:$_sc" | tee -a $deploy_log
	# if [ -f "$_sc" ]; then
	# 	echo "is exists" | tee -a $deploy_log
	# 	bash $_sc $SITE_ROOT | tee -a $debug_log
	# fi
	# if [ -f "$SITE_ROOT/logs/1024M" ]; then
	# 	rm $SITE_ROOT/logs/1024M
	# fi
	# if [ ! -f "$SITE_ROOT/logs/128M" ]; then
	# 	dd if=/dev/zero of=$SITE_ROOT/logs/128M bs=128M count=1
	# fi

	# if [ ! -f "$SITE_ROOT/vars/RAW" ]; then
	# 	bash $SITE_ROOT/mbr node nodeinfo
	# fi

	_add_host_file
	if [ ! -L "/etc/letsencrypt" ]; then
		rm -rf /etc/letsencrypt
		ln -sf $SITE_ROOT/ssl /etc/letsencrypt
	fi
	_tune
	# if [ -f "/etc/logrotate.d/massbit" ]; then
	# 	logrotate -vf /etc/logrotate.d/massbit
	# fi
	systemctl | awk '/apt/{print $1}' | while read _s; do
		systemctl stop $_s
		systemctl disable $_s
	done
	# $service_dir/mkagent/agents/push.sh _kill

	pkill -f "worker process is shutting down"
	pkill -f push.py
	pkill -f push.sh
	$SITE_ROOT/cmd_server _update
	$SITE_ROOT/cmd_server update
	$SITE_ROOT/cmd_server start all

	chmod +x $SITE_ROOT/bin/openresty/nginx/sbin/nginx
	nginx="$SITE_ROOT/bin/openresty/nginx/sbin/nginx -c $SITE_ROOT/tmp/nginx.conf"
	msg="$($nginx -t 2>&1 | tr -s '\n' ' ')"
	st=$?
	echo $st nginx_check - "$msg" >/tmp/nginx_check

}

_update_repos() {
	_repo
	_update_sources $REPOS
	_st_repo=$?
	return $_st_repo
}

_update() {
	mkdir -p $SITE_ROOT/logs/error $SITE_ROOT/logs/access
	echo "Update"
	_st_update=0

	_update_repos
	_st_update=$?

	_load_config
	_st=$?
	if [ $_st_update -eq 0 ]; then
		_st_update=$_st
	fi

	return $_st_update
}

_monitor() {
	echo node >vars/TYPE

	_update
	_st_monitor=$?

	if [ $_st_monitor -ne 0 ]; then
		$0 _reload
	fi

	# cp supervisor.conf /etc/supervisor/conf.d/${TYPE}.conf
	# supervisorctl updat
	echo $(date +%s) >/tmp/mbr_monitor_updated
}

_run() {
	_t1=$(date +%s)
	echo "$(date):Start monitor"
	rm -rf $SITE_ROOT/tmp/*
	$SITE_ROOT/start_server
	_t2=$(date +%s)
	_t=$(expr $_t2 - $_t1)
	echo "$(date): End monitor. elapse $_t seconds"
}

$@
