#!/bin/bash
mkdir vars logs
_run_env() {
	TYPE=$1
	docker run -d -t -i --rm \
		-p "443:443" \
		--name "mbr_${TYPE}" \
		-e "ENV=" \
		-e "ID=" \
		-e "USER_ID=" \
		-e "BLOCKCHAIN=" \
		-e "NETWORK=" \
		-e "ZONE=" \
		-e "APP_KEY=" \
		-e "PORTAL_URL=" \
		-v "$PWD/logs:/massbit/massbitroute/app/src/sites/services/$TYPE/logs:rw" \
		-v "$PWD/vars:/massbit/massbitroute/app/src/sites/services/$TYPE/vars:rw" \
		massbit/massbitroute_${TYPE}:latest
}
_run_cmd() {
	TYPE=$1
	CMD=$2
	docker run -d -t -i --rm \
		-p "443:443" \
		--name "mbr_${TYPE}" \
		-e "INSTALL_CMD=$CMD" \
		-v "$PWD/logs:/massbit/massbitroute/app/src/sites/services/$TYPE/logs:rw" \
		-v "$PWD/vars:/massbit/massbitroute/app/src/sites/services/$TYPE/vars:rw" \
		massbit/massbitroute_${TYPE}:latest
}
$@

#example
#_run_cmd node "https://portal.massbitroute.net/api/v1/node_install?id=a1f1c1a9-e7ad-4d29-ac71-0cb3b0c57225&user_id=b363ddf4-42cf-4ccf-89c2-8c42c531ac99&blockchain=eth&network=mainnet&zone=AS&data_url=http://34.81.232.186:8545&app_key=D61VyZiUcNX8DUWNvIyyBA&portal_url=https://portal.massbitroute.net&env=keiko"
